# Generated by Django 5.2.4 on 2025-07-14 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="advertisement_id",
            new_name="advertisement",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "advertisement")},
        ),
    ]
